Repository Adrian-Hawkins/EyesOnspectacularCode, pull requests merged in 2024-04, with the labels that each got.

#1 Bot
  .dockerignore
  .github/workflows/bot.yml
  .gitignore
  EOSC.Bot/Classes/DiscordBot.cs
  EOSC.Bot/Commands/EchoCommand.cs
  EOSC.Bot/Commands/HelloCommand.cs
  EOSC.Bot/Dockerfile
  EOSC.Bot/EOSC.Bot.csproj
  EOSC.Bot/Interfaces/Classes/IDiscordBot.cs
  EOSC.Bot/Interfaces/Commands/IBotCommand.cs
  EOSC.Bot/Program.cs
  Terraform/.terraform.lock.hcl
  Terraform/ec2.tf
  Terraform/rds.tf
  Terraform/security_group.tf
Labels: enhancement

#2 feat: :lock: Grab discord token from env
  EOSC.Bot/Classes/DiscordBot.cs
Labels: enhancement

#5 Feature/spec 14 host web
  .github/workflows/build_web.yml
  .github/workflows/deploy_web.yml
  EOSC.Web/Dockerfile
Labels: enhancement

#6 Feature/web
  EOSC.Web/Components/App.razor
  EOSC.Web/Components/Layout/NavMenu.razor
  EOSC.Web/Components/Layout/NavMenu.razor.css
  EOSC.Web/Components/Pages/Base64Decode.razor
  EOSC.Web/Components/_Imports.razor
  EOSC.Web/Program.cs
Labels: enhancement

#9 Fix/hosting
  .github/workflows/deploy_bot.yml
  .github/workflows/deploy_web.yml
  EOSC.Bot/Dockerfile
  EOSC.Bot/EOSC.Bot.csproj
  EOSC.Bot/Program.cs
  EOSC.Common/Constant/Hello.cs
  EOSC.Web/Dockerfile
  EOSC.Web/EOSC.Web.csproj
Labels: bug

#10 fix: :rocket: Fixed common project
  EOSC.API/EOSC.API.csproj
  EOSC.Common/EOSC.Common.csproj
  EOSC.sln
Labels: bug

#11 docs: :hammer: Added swagger to prod for testing
  EOSC.API/Program.cs
Labels: documentation

#14 Feature/spec 22 dt formatter
  .github/workflows/deploy_bot.yml
  .github/workflows/deploy_web.yml
  EOSC.API/Controllers/DatetimeController.cs
  EOSC.Bot/Commands/DateTimeCommand.cs
  EOSC.Bot/EOSC.Bot.csproj
  EOSC.Common/Config/APIEndpoint.cs
  EOSC.Common/EOSC.Common.csproj
  EOSC.Common/Requests/DatetimeRequest.cs
  EOSC.Common/Responses/DatetimeResponse.cs
  EOSC.Common/Services/DateTimeService.cs
  EOSC.Web/Components/Layout/NavMenu.razor
  EOSC.Web/Components/Pages/Datetime.razor
  EOSC.Web/Program.cs
  EOSC.sln
Labels: enhancement

#15 Feature/bot improvements
  EOSC.Bot/Attributes/CommandAttribute.cs
  EOSC.Bot/Classes/Deserializers/Author.cs
  EOSC.Bot/Classes/Deserializers/BaseMessage.cs
  EOSC.Bot/Classes/Deserializers/HeartBeat.cs
  EOSC.Bot/Classes/Deserializers/Message.cs
  EOSC.Bot/Classes/DiscordBot.cs
  EOSC.Bot/Commands/BaseCommand.cs
  EOSC.Bot/Commands/DateTimeCommand.cs
  EOSC.Bot/Commands/EchoCommand.cs
  EOSC.Bot/Commands/HelloCommand.cs
  EOSC.Bot/Interfaces/Classes/IDiscordBot.cs
  EOSC.Bot/Interfaces/Commands/IBotCommand.cs
  EOSC.Bot/Program.cs
  EOSC.Common/EOSC.Common.csproj
  EOSC.Common/Services/DateTimeService.cs
Labels: documentation, enhancement

#16 Feature/spec 22 dt formatter
  EOSC.Bot/Classes/DiscordBot.cs
  EOSC.Bot/Commands/DateTimeCommand.cs
  EOSC.Bot/Commands/EchoCommand.cs
  EOSC.Bot/EOSC.Bot.csproj
  EOSC.Bot/Interfaces/Classes/IDiscordBot.cs
  EOSC.Bot/Program.cs
Labels: enhancement

#17 Feature/database
  .github/workflows/deploy_api.yml
  EOSC.API/Attributes/ToolAttribute.cs
  EOSC.API/Controllers/DatetimeController.cs
  EOSC.API/Controllers/HistoryController.cs
  EOSC.API/EOSC.API.csproj
  EOSC.API/Middleware/RequestCompletedMiddleware.cs
  EOSC.API/Program.cs
  EOSC.API/Repo/HistoryRepo.cs
  EOSC.API/Repo/IHistoryRepo.cs
  EOSC.API/Service/HistoryService.cs
  EOSC.API/Service/IHistoryService.cs
  EOSC.Common/Config/DB.cs
  EOSC.Common/EOSC.Common.csproj
  EOSC.Common/SharedRepository/Connection.cs
Labels: documentation, enhancement

#20 Feature/history fe
  EOSC.API/Controllers/HistoryController.cs
  EOSC.API/Program.cs
  EOSC.Bot/Classes/DiscordBot.cs
  EOSC.Bot/Commands/BaseCommand.cs
  EOSC.Bot/Commands/DateTimeCommand.cs
  EOSC.Bot/Commands/GetHistoryCommand.cs
  EOSC.Bot/Commands/HelloCommand.cs
  EOSC.Common/Responses/HistoryResponse.cs
  EOSC.Common/Services/ApiCallService.cs
  EOSC.Common/Services/HistoryService.cs
Labels: bug

#32 Feature/yaml to json
  EOSC.API/Controllers/JsonToYamlController.cs
  EOSC.API/Controllers/YamlToJsonController.cs
  EOSC.Bot/Commands/JsonToYaml.cs
  EOSC.Bot/Commands/YamlTojsonCommand.cs
  EOSC.Common/Requests/YamlToJsonRequest.cs
  EOSC.Common/Responses/YamlToJsonResponse.cs
  EOSC.Web/Components/Layout/NavMenu.razor
  EOSC.Web/Components/Pages/Converter.razor
  EOSC.Web/Components/Pages/Home.razor
  EOSC.Web/Components/Pages/JsonConverter.razor
  EOSC.Web/Program.cs
Labels: enhancement

#36 feature/auth_token
  EOSC.API/Infra/JwtAuthManager.cs
  EOSC.Common/Constant/JwtAuthResult.cs
  EOSC.Web/Components/Pages/Login.razor
  EOSC.Web/EOSC.Web.csproj
Labels: bug

#37 Create HelpCommand.cs
  EOSC.Bot/Commands/HelpCommand.cs
Labels: enhancement

#39 Feature/auth token
  EOSC.Bot/Commands/YamlTojsonCommand.cs
Labels: bug

#41 truncated history
  EOSC.API/Controllers/HistoryController.cs
  EOSC.Bot/Commands/GetHistoryCommand.cs
Labels: bug

#44 Added history link
  EOSC.API/Controllers/HistoryController.cs
  EOSC.Web/Components/Layout/NavMenu.razor
Labels: enhancement
